#!/bin/bash

### Manual script to cleanup databases, users, and roles generated by the inspec profile ###
echo "--- Cleaning up InSpec artifacts ---"

# Variables
CONTAINER_NAME="mongo-hardened"
MONGO_DBA="root"
MONGO_DBA_PASSWORD="root"
MONGO_HOST="localhost"
MONGO_PORT="27017"
CA_FILE="/etc/ssl/CA_bundle.pem"
CERTIFICATE_KEY_FILE="/etc/ssl/mongodb.pem"
AUTH_MECHANISM="SCRAM-SHA-256"

# Commands
DROP_TEST_USER_COMMAND="db.getSiblingDB('test').dropUser('myTester')"
DROP_PRODUCTS_DB_COMMAND="db.getSiblingDB('products').dropDatabase()"

echo "Dropping the 'myTester' user from the 'test' database:"
docker exec -it $CONTAINER_NAME mongosh "mongodb://$MONGO_DBA:$MONGO_DBA_PASSWORD@$MONGO_HOST:$MONGO_PORT/?authMechanism=$AUTH_MECHANISM&tls=true&tlsCAFile=$CA_FILE&tlsCertificateKeyFile=$CERTIFICATE_KEY_FILE" --quiet --eval "$DROP_TEST_USER_COMMAND"

echo "Dropping the 'products' database:"
docker exec -it $CONTAINER_NAME mongosh "mongodb://$MONGO_DBA:$MONGO_DBA_PASSWORD@$MONGO_HOST:$MONGO_PORT/?authMechanism=$AUTH_MECHANISM&tls=true&tlsCAFile=$CA_FILE&tlsCertificateKeyFile=$CERTIFICATE_KEY_FILE" --quiet --eval "$DROP_PRODUCTS_DB_COMMAND"
